# Generated by Django 5.0.14 on 2026-08-25 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('inquiry_type', models.CharField(choices=[('general', 'General'), ('sales', 'Sales'), ('technical_support', 'Technical Support'), ('quotation', 'Quotation'), ('material_submittal', 'Material Submittal'), ('distributor', 'Distributor / Partnership')], default='general', max_length=30)),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='products.product')),
            ],
            options={
                'verbose_name_plural': 'contact inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='inquiries_c_status_c65802_idx'), models.Index(fields=['created_at'], name='inquiries_c_created_5a12f3_idx')],
            },
        ),
    ]
