# Generated by Django 5.0.14 on 2026-08-25 08:58

import apps.documents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('document_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('document_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('catalogue', 'Catalogue'), ('material_submittal', 'Material Submittal'), ('certificate', 'Certificate'), ('test_report', 'Test Report'), ('installation_guide', 'Installation Guide'), ('warranty', 'Warranty'), ('company_profile', 'Company Profile'), ('technical_manual', 'Technical Manual'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('en_ar', 'English / Arabic')], default='en', max_length=10)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='documents/covers/')),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('public', models.BooleanField(db_index=True, default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Product family this document belongs to (used for filtering even when not tied to a single product, e.g. a catalogue).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='products.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='products.product')),
                ('standards', models.ManyToManyField(blank=True, related_name='documents', to='products.standard')),
            ],
            options={
                'ordering': ['-featured', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.CharField(help_text="Human label, e.g. 'Rev 04'.", max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0, help_text='Bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 hex digest', max_length=64)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('current', 'Current'), ('archived', 'Archived')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentrevision'),
        ),
        migrations.AddIndex(
            model_name='documentrevision',
            index=models.Index(fields=['document'], name='documents_d_documen_a34dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentrevision',
            index=models.Index(fields=['status'], name='documents_d_status_ac9253_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='unique_document_version'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['slug'], name='documents_d_slug_3df491_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_d_documen_40c475_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['active', 'public'], name='documents_d_active_21801f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['product'], name='documents_d_product_8a20bf_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category'], name='documents_d_categor_fec314_idx'),
        ),
    ]
