# Generated by Django 5.0.14 on 2026-08-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrevision',
            name='version',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-assigned on create (next integer for this document) -- leave blank.', null=True),
        ),
    ]
