# Generated by Django 5.0.14 on 2026-08-25 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentrevision_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='section',
            field=models.ForeignKey(blank=True, help_text="Curated Technical Library grouping (datasheets only, e.g. 'Water Supply').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documentsection'),
        ),
    ]
